apiVersion: v1
kind: Service
metadata:
  name: communities-platform-backend
  labels:
    app: communities-platform-argo
spec:
  type: ClusterIP
  selector:
    app: communities-platform-argo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
